# Generated by Django 5.0.6 on 2024-06-01 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('price', models.IntegerField(default=0, verbose_name='售價')),
                ('stars', models.IntegerField(default=0, verbose_name='總星數')),
                ('sales', models.IntegerField(default=0, verbose_name='總銷售量')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='帳號')),
                ('password', models.CharField(max_length=128, verbose_name='密碼')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Order_System.food', verbose_name='品項')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Pre_Order_System.member', verbose_name='會員')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pre_Order_System.food', verbose_name='品項')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Pre_Order_System.member', verbose_name='會員')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='Pre_Order_System.restaurant', verbose_name='店家'),
        ),
    ]
