# Generated by Django 5.0.6 on 2024-06-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Order_System', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
    ]
