# Generated by Django 5.0.6 on 2024-06-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Order_System', '0002_remove_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(null=True, upload_to='food_images/', verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(null=True, upload_to='restaurant_images/', verbose_name='圖片'),
        ),
    ]
