# Generated by Django 5.0.6 on 2024-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pre_Order_System', '0005_alter_food_img_alter_restaurant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(default='food_images/default_food.jpg', null=True, upload_to='food_images/', verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(default='restaurant_images/default_restaurant.jpg', null=True, upload_to='restaurant_images/', verbose_name='圖片'),
        ),
    ]
